version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql-galeria
    restart: always
    environment:
      MYSQL_DATABASE: galeria
      MYSQL_ROOT_PASSWORD: 12456
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

  backend:
    build: ./backend
    container_name: galeria-backend
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      - mysql
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/galeria
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: 12456
      SPRING_JPA_HIBERNATE_DDL_AUTO: update

volumes:
  db_data:
